/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "var(--surface-bright)",
        "on-surface": "var(--on-surface)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "on-error-container": "var(--on-error-container)",
        "surface-container": "var(--surface-container)",
        "surface-container-high": "var(--surface-container-high)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "outline-variant": "var(--outline-variant)",
        "on-error": "var(--on-error)",
        "error-container": "var(--error-container)",
        "secondary-fixed": "var(--secondary-fixed)",
        "primary-container": "var(--primary-container)",
        "secondary": "var(--secondary)",
        "surface-container-low": "var(--surface-container-low)",
        "inverse-primary": "var(--inverse-primary)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-primary": "var(--on-primary)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "surface-dim": "var(--surface-dim)",
        "outline": "var(--outline)",
        "background": "var(--background)",
        "primary": "var(--primary)",
        "error": "var(--error)",
        "on-primary-container": "var(--on-primary-container)",
        "on-background": "var(--on-background)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "on-secondary-container": "var(--on-secondary-container)",
        "surface-variant": "var(--surface-variant)",
        "on-surface-variant": "var(--on-surface-variant)",
        "tertiary": "var(--tertiary)",
        "on-secondary": "var(--on-secondary)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "inverse-surface": "var(--inverse-surface)",
        "surface-tint": "var(--surface-tint)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-tertiary": "var(--on-tertiary)",
        "surface": "var(--surface)",
        "tertiary-container": "var(--tertiary-container)",
        "primary-fixed": "var(--primary-fixed)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "secondary-container": "var(--secondary-container)",
        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "on-secondary-fixed": "var(--on-secondary-fixed)"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "md": "24px",
        "gutter": "24px",
        "margin": "32px",
        "xs": "4px",
        "base": "8px",
        "lg": "48px",
        "xl": "80px",
        "sm": "12px"
      },
      fontFamily: {
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-md": ["Manrope", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "body-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "tajawal": ["Tajawal", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }],
        "label-sm": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
