const logger = require('../utils/logger');

const PROMPT_VERSION = "v2.0";

/**
 * Validates and filters user input for dangerous or destructive prompts
 * @param {string} prompt - Tenant input prompt
 * @returns {Object} { allowed: boolean, filteredPrompt: string, reason: string }
 */
function applyPolicyFilter(prompt) {
  const normalized = (prompt || '').toLowerCase();
  
  // Destructive operations check
  const destructivePatterns = [
    'حذف الكل', 'امسح الكل', 'delete all', 'drop table', 'truncate', 
    'حذف جميع المنتجات', 'حذف المتجر', 'امسح المنتجات', 'delete products'
  ];

  for (const pattern of destructivePatterns) {
    if (normalized.includes(pattern)) {
      logger.warn(`[AI Guardrail] Destructive query blocked: "${prompt}"`);
      return {
        allowed: false,
        filteredPrompt: prompt,
        reason: "عذراً، لا يمكنني تنفيذ عمليات الحذف الشامل أو العمليات التدميرية للمتجر حفاظاً على بياناتك."
      };
    }
  }

  return {
    allowed: true,
    filteredPrompt: prompt,
    reason: null
  };
}

/**
 * Checks draft action payloads for business rules compliance
 * @param {Object} action - Action generated by Gemini
 * @returns {Object} The validated and potentially modified action
 */
function sanitizeActionDraft(action) {
  if (!action || !action.type) return action;

  if (action.type === 'create_coupon' && action.payload) {
    // Discount cap rule: Max 50% discount drafted automatically
    const pct = Number(action.payload.discount_percentage || 0);
    if (pct > 50) {
      logger.warn(`[AI Guardrail] Capping coupon discount from ${pct}% to 50%`);
      action.payload.discount_percentage = 50;
      action.label = action.label.replace(new RegExp(`${pct}%`, 'g'), '50%');
    }
  }

  return action;
}

module.exports = {
  PROMPT_VERSION,
  applyPolicyFilter,
  sanitizeActionDraft
};
