const EventTypes = Object.freeze({
    FEATURE_CONSUMED: 'FEATURE_CONSUMED',
    FEATURE_REFUNDED: 'FEATURE_REFUNDED',
    MEMBERSHIP_CREATED: 'MEMBERSHIP_CREATED',
    MEMBERSHIP_ACTIVATED: 'MEMBERSHIP_ACTIVATED',
    MEMBERSHIP_SUSPENDED: 'MEMBERSHIP_SUSPENDED',
    IDENTITY_CREATED: 'IDENTITY_CREATED',
    POLICY_DENIED: 'POLICY_DENIED'
});

module.exports = { EventTypes };
