-- Comprehensive schema update for site_settings

ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS flash_sale_active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS flash_sale_title text DEFAULT 'عرض اليوم! 🔥',
  ADD COLUMN IF NOT EXISTS flash_sale_desc text DEFAULT 'خصم 15% على جميع القطع',
  ADD COLUMN IF NOT EXISTS flash_sale_end_time text,
  ADD COLUMN IF NOT EXISTS social_proof_active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS social_proof_demo boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS cross_sell_active boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS cross_sell_demo boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS low_stock_warning_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS low_stock_threshold integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS live_view_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS live_view_base integer DEFAULT 15,
  ADD COLUMN IF NOT EXISTS today_sales_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS today_sales_count integer DEFAULT 87,
  ADD COLUMN IF NOT EXISTS free_shipping_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS free_shipping_threshold integer DEFAULT 500,
  ADD COLUMN IF NOT EXISTS guarantee_badge_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS guarantee_text text DEFAULT 'ضمان سنتين على جميع المنتجات',
  ADD COLUMN IF NOT EXISTS brand_name text DEFAULT 'EG-PARTS',
  ADD COLUMN IF NOT EXISTS logo_url text,
  ADD COLUMN IF NOT EXISTS favicon_url text,
  ADD COLUMN IF NOT EXISTS whatsapp_number text,
  ADD COLUMN IF NOT EXISTS support_email text,
  ADD COLUMN IF NOT EXISTS store_address text,
  ADD COLUMN IF NOT EXISTS facebook_url text,
  ADD COLUMN IF NOT EXISTS instagram_url text,
  ADD COLUMN IF NOT EXISTS tiktok_url text,
  ADD COLUMN IF NOT EXISTS theme_colors jsonb,
  ADD COLUMN IF NOT EXISTS hot_deals jsonb;
