-- Seed all realistic plan limits
INSERT INTO public.plans (code, display_name, price_monthly, price_yearly, trial_days, trial_enabled, is_public, is_default, sort_order)
VALUES 
  ('free', 'خطة مجانية', 0, 0, 0, false, true, false, 0),
  ('basic', 'باقة أساسية', 249, 2490, 0, false, true, false, 1),
  ('starter', 'Starter', 499, 4990, 0, false, true, true, 2),
  ('growth', 'Growth', 899, 8990, 14, true, true, false, 3),
  ('scale', 'Scale', 1699, 16990, 14, true, true, false, 4),
  ('enterprise', 'Enterprise', 4999, 29998, 0, false, false, false, 5)
ON CONFLICT (code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  price_monthly = EXCLUDED.price_monthly,
  price_yearly = EXCLUDED.price_yearly,
  trial_days = EXCLUDED.trial_days,
  trial_enabled = EXCLUDED.trial_enabled,
  is_public = EXCLUDED.is_public,
  is_default = EXCLUDED.is_default,
  sort_order = EXCLUDED.sort_order;

WITH seed_data(plan_code, feature_key, limit_type, limit_config) AS (
  VALUES
  ('free', 'products', 'count', '{"max_value":15}'::jsonb),
  ('free', 'categories', 'count', '{"max_value":3}'::jsonb),
  ('free', 'brands', 'count', '{"max_value":2}'::jsonb),
  ('free', 'product_images', 'count', '{"max_value":30}'::jsonb),
  ('free', 'product_variants', 'count', '{"max_value":15}'::jsonb),
  ('free', 'attributes', 'count', '{"max_value":10}'::jsonb),
  ('free', 'branches', 'count', '{"max_value":1}'::jsonb),
  ('free', 'warehouses', 'count', '{"max_value":1}'::jsonb),
  ('free', 'shelves', 'count', '{"max_value":5}'::jsonb),
  ('free', 'employees', 'count', '{"max_value":1}'::jsonb),
  ('free', 'staff_users', 'count', '{"max_value":1}'::jsonb),
  ('free', 'roles', 'count', '{"max_value":0}'::jsonb),
  ('free', 'customers', 'count', '{"max_value":50}'::jsonb),
  ('free', 'suppliers', 'count', '{"max_value":2}'::jsonb),
  ('free', 'orders', 'count', '{"max_value":30}'::jsonb),
  ('free', 'orders_per_month', 'count', '{"max_value":15}'::jsonb),
  ('free', 'active_orders', 'count', '{"max_value":5}'::jsonb),
  ('free', 'coupons', 'boolean', '{"enabled":false}'::jsonb),
  ('free', 'discount_campaigns', 'count', '{"max_value":0}'::jsonb),
  ('free', 'return_requests', 'count', '{"max_value":5}'::jsonb),
  ('free', 'storage_bytes', 'count', '{"max_value":268435456}'::jsonb),
  ('free', 'r2_storage', 'count', '{"max_value":268435456}'::jsonb),
  ('free', 'uploaded_images', 'count', '{"max_value":50}'::jsonb),
  ('free', 'uploaded_files', 'count', '{"max_value":10}'::jsonb),
  ('free', 'uploads', 'count', '{"max_value":20}'::jsonb),
  ('free', 'banner_images', 'count', '{"max_value":2}'::jsonb),
  ('free', 'logos', 'count', '{"max_value":1}'::jsonb),
  ('free', 'custom_domains', 'boolean', '{"enabled":false}'::jsonb),
  ('free', 'custom_domain', 'boolean', '{"enabled":false}'::jsonb),
  ('free', 'api_keys', 'count', '{"max_value":0}'::jsonb),
  ('free', 'webhooks', 'count', '{"max_value":0}'::jsonb),
  ('free', 'integrations', 'count', '{"max_value":0}'::jsonb),
  ('free', 'payment_gateways', 'boolean', '{"enabled":false}'::jsonb),
  ('free', 'api_requests_day', 'count', '{"max_value":100}'::jsonb),
  ('free', 'export_formats', 'export_formats', '{"allowed_formats":"csv"}'::jsonb),
  ('free', 'ai_requests_month', 'count', '{"max_value":10}'::jsonb),
  ('free', 'forecast_jobs', 'count', '{"max_value":0}'::jsonb),
  ('free', 'report_generation', 'count', '{"max_value":2}'::jsonb),
  ('free', 'analytics_exports', 'count', '{"max_value":1}'::jsonb),
  ('free', 'copilot_messages_day', 'count', '{"max_value":10}'::jsonb),
  ('free', 'otp_messages_month', 'count', '{"max_value":20}'::jsonb),
  ('free', 'email_messages_month', 'count', '{"max_value":50}'::jsonb),
  ('free', 'push_notifications_month', 'count', '{"max_value":50}'::jsonb),
  ('free', 'whatsapp_enabled', 'boolean', '{"enabled":true}'::jsonb),
  ('free', 'whatsapp_accounts_max', 'count', '{"max_value":1}'::jsonb),
  ('free', 'whatsapp_messages_month', 'count', '{"max_value":50}'::jsonb),
  ('free', 'whatsapp_concurrency', 'count', '{"max_value":1}'::jsonb),
  ('free', 'whatsapp_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('free', 'whatsapp_customer_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('free', 'platform_billing', 'boolean', '{"enabled":false}'::jsonb),
  ('basic', 'products', 'count', '{"max_value":100}'::jsonb),
  ('basic', 'categories', 'count', '{"max_value":10}'::jsonb),
  ('basic', 'brands', 'count', '{"max_value":10}'::jsonb),
  ('basic', 'product_images', 'count', '{"max_value":300}'::jsonb),
  ('basic', 'product_variants', 'count', '{"max_value":150}'::jsonb),
  ('basic', 'attributes', 'count', '{"max_value":50}'::jsonb),
  ('basic', 'branches', 'count', '{"max_value":1}'::jsonb),
  ('basic', 'warehouses', 'count', '{"max_value":1}'::jsonb),
  ('basic', 'shelves', 'count', '{"max_value":20}'::jsonb),
  ('basic', 'employees', 'count', '{"max_value":2}'::jsonb),
  ('basic', 'staff_users', 'count', '{"max_value":2}'::jsonb),
  ('basic', 'roles', 'count', '{"max_value":1}'::jsonb),
  ('basic', 'customers', 'count', '{"max_value":300}'::jsonb),
  ('basic', 'suppliers', 'count', '{"max_value":10}'::jsonb),
  ('basic', 'orders', 'count', '{"max_value":200}'::jsonb),
  ('basic', 'orders_per_month', 'count', '{"max_value":100}'::jsonb),
  ('basic', 'active_orders', 'count', '{"max_value":20}'::jsonb),
  ('basic', 'coupons', 'boolean', '{"enabled":true}'::jsonb),
  ('basic', 'discount_campaigns', 'count', '{"max_value":3}'::jsonb),
  ('basic', 'return_requests', 'count', '{"max_value":20}'::jsonb),
  ('basic', 'storage_bytes', 'count', '{"max_value":1073741824}'::jsonb),
  ('basic', 'r2_storage', 'count', '{"max_value":1073741824}'::jsonb),
  ('basic', 'uploaded_images', 'count', '{"max_value":300}'::jsonb),
  ('basic', 'uploaded_files', 'count', '{"max_value":50}'::jsonb),
  ('basic', 'uploads', 'count', '{"max_value":100}'::jsonb),
  ('basic', 'banner_images', 'count', '{"max_value":5}'::jsonb),
  ('basic', 'logos', 'count', '{"max_value":2}'::jsonb),
  ('basic', 'custom_domains', 'boolean', '{"enabled":false}'::jsonb),
  ('basic', 'custom_domain', 'boolean', '{"enabled":false}'::jsonb),
  ('basic', 'api_keys', 'count', '{"max_value":0}'::jsonb),
  ('basic', 'webhooks', 'count', '{"max_value":0}'::jsonb),
  ('basic', 'integrations', 'count', '{"max_value":1}'::jsonb),
  ('basic', 'payment_gateways', 'boolean', '{"enabled":false}'::jsonb),
  ('basic', 'api_requests_day', 'count', '{"max_value":500}'::jsonb),
  ('basic', 'export_formats', 'export_formats', '{"allowed_formats":"csv,excel"}'::jsonb),
  ('basic', 'ai_requests_month', 'count', '{"max_value":50}'::jsonb),
  ('basic', 'forecast_jobs', 'count', '{"max_value":2}'::jsonb),
  ('basic', 'report_generation', 'count', '{"max_value":10}'::jsonb),
  ('basic', 'analytics_exports', 'count', '{"max_value":5}'::jsonb),
  ('basic', 'copilot_messages_day', 'count', '{"max_value":25}'::jsonb),
  ('basic', 'otp_messages_month', 'count', '{"max_value":150}'::jsonb),
  ('basic', 'email_messages_month', 'count', '{"max_value":300}'::jsonb),
  ('basic', 'push_notifications_month', 'count', '{"max_value":300}'::jsonb),
  ('basic', 'whatsapp_enabled', 'boolean', '{"enabled":true}'::jsonb),
  ('basic', 'whatsapp_accounts_max', 'count', '{"max_value":1}'::jsonb),
  ('basic', 'whatsapp_messages_month', 'count', '{"max_value":300}'::jsonb),
  ('basic', 'whatsapp_concurrency', 'count', '{"max_value":2}'::jsonb),
  ('basic', 'whatsapp_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('basic', 'whatsapp_customer_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('basic', 'platform_billing', 'boolean', '{"enabled":false}'::jsonb),
  ('starter', 'products', 'count', '{"max_value":500}'::jsonb),
  ('starter', 'categories', 'count', '{"max_value":30}'::jsonb),
  ('starter', 'brands', 'count', '{"max_value":30}'::jsonb),
  ('starter', 'product_images', 'count', '{"max_value":1500}'::jsonb),
  ('starter', 'product_variants', 'count', '{"max_value":800}'::jsonb),
  ('starter', 'attributes', 'count', '{"max_value":200}'::jsonb),
  ('starter', 'branches', 'count', '{"max_value":2}'::jsonb),
  ('starter', 'warehouses', 'count', '{"max_value":2}'::jsonb),
  ('starter', 'shelves', 'count', '{"max_value":50}'::jsonb),
  ('starter', 'employees', 'count', '{"max_value":5}'::jsonb),
  ('starter', 'staff_users', 'count', '{"max_value":5}'::jsonb),
  ('starter', 'roles', 'count', '{"max_value":3}'::jsonb),
  ('starter', 'customers', 'count', '{"max_value":1500}'::jsonb),
  ('starter', 'suppliers', 'count', '{"max_value":30}'::jsonb),
  ('starter', 'orders', 'count', '{"max_value":1000}'::jsonb),
  ('starter', 'orders_per_month', 'count', '{"max_value":500}'::jsonb),
  ('starter', 'active_orders', 'count', '{"max_value":50}'::jsonb),
  ('starter', 'coupons', 'boolean', '{"enabled":true}'::jsonb),
  ('starter', 'discount_campaigns', 'count', '{"max_value":10}'::jsonb),
  ('starter', 'return_requests', 'count', '{"max_value":50}'::jsonb),
  ('starter', 'storage_bytes', 'count', '{"max_value":3221225472}'::jsonb),
  ('starter', 'r2_storage', 'count', '{"max_value":3221225472}'::jsonb),
  ('starter', 'uploaded_images', 'count', '{"max_value":1500}'::jsonb),
  ('starter', 'uploaded_files', 'count', '{"max_value":200}'::jsonb),
  ('starter', 'uploads', 'count', '{"max_value":300}'::jsonb),
  ('starter', 'banner_images', 'count', '{"max_value":10}'::jsonb),
  ('starter', 'logos', 'count', '{"max_value":3}'::jsonb),
  ('starter', 'custom_domains', 'boolean', '{"enabled":true}'::jsonb),
  ('starter', 'custom_domain', 'boolean', '{"enabled":true}'::jsonb),
  ('starter', 'api_keys', 'count', '{"max_value":1}'::jsonb),
  ('starter', 'webhooks', 'count', '{"max_value":2}'::jsonb),
  ('starter', 'integrations', 'count', '{"max_value":3}'::jsonb),
  ('starter', 'payment_gateways', 'boolean', '{"enabled":true}'::jsonb),
  ('starter', 'api_requests_day', 'count', '{"max_value":2000}'::jsonb),
  ('starter', 'export_formats', 'export_formats', '{"allowed_formats":"csv,excel,pdf"}'::jsonb),
  ('starter', 'ai_requests_month', 'count', '{"max_value":150}'::jsonb),
  ('starter', 'forecast_jobs', 'count', '{"max_value":5}'::jsonb),
  ('starter', 'report_generation', 'count', '{"max_value":30}'::jsonb),
  ('starter', 'analytics_exports', 'count', '{"max_value":15}'::jsonb),
  ('starter', 'copilot_messages_day', 'count', '{"max_value":50}'::jsonb),
  ('starter', 'otp_messages_month', 'count', '{"max_value":600}'::jsonb),
  ('starter', 'email_messages_month', 'count', '{"max_value":1000}'::jsonb),
  ('starter', 'push_notifications_month', 'count', '{"max_value":1000}'::jsonb),
  ('starter', 'whatsapp_enabled', 'boolean', '{"enabled":true}'::jsonb),
  ('starter', 'whatsapp_accounts_max', 'count', '{"max_value":2}'::jsonb),
  ('starter', 'whatsapp_messages_month', 'count', '{"max_value":1000}'::jsonb),
  ('starter', 'whatsapp_concurrency', 'count', '{"max_value":3}'::jsonb),
  ('starter', 'whatsapp_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('starter', 'whatsapp_customer_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('starter', 'platform_billing', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'products', 'count', '{"max_value":2500}'::jsonb),
  ('growth', 'categories', 'count', '{"max_value":100}'::jsonb),
  ('growth', 'brands', 'count', '{"max_value":100}'::jsonb),
  ('growth', 'product_images', 'count', '{"max_value":8000}'::jsonb),
  ('growth', 'product_variants', 'count', '{"max_value":4000}'::jsonb),
  ('growth', 'attributes', 'count', '{"max_value":1000}'::jsonb),
  ('growth', 'branches', 'count', '{"max_value":5}'::jsonb),
  ('growth', 'warehouses', 'count', '{"max_value":5}'::jsonb),
  ('growth', 'shelves', 'count', '{"max_value":200}'::jsonb),
  ('growth', 'employees', 'count', '{"max_value":12}'::jsonb),
  ('growth', 'staff_users', 'count', '{"max_value":12}'::jsonb),
  ('growth', 'roles', 'count', '{"max_value":10}'::jsonb),
  ('growth', 'customers', 'count', '{"max_value":10000}'::jsonb),
  ('growth', 'suppliers', 'count', '{"max_value":100}'::jsonb),
  ('growth', 'orders', 'count', '{"max_value":5000}'::jsonb),
  ('growth', 'orders_per_month', 'count', '{"max_value":2500}'::jsonb),
  ('growth', 'active_orders', 'count', '{"max_value":150}'::jsonb),
  ('growth', 'coupons', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'discount_campaigns', 'count', '{"max_value":30}'::jsonb),
  ('growth', 'return_requests', 'count', '{"max_value":200}'::jsonb),
  ('growth', 'storage_bytes', 'count', '{"max_value":10737418240}'::jsonb),
  ('growth', 'r2_storage', 'count', '{"max_value":10737418240}'::jsonb),
  ('growth', 'uploaded_images', 'count', '{"max_value":8000}'::jsonb),
  ('growth', 'uploaded_files', 'count', '{"max_value":1000}'::jsonb),
  ('growth', 'uploads', 'count', '{"max_value":1000}'::jsonb),
  ('growth', 'banner_images', 'count', '{"max_value":20}'::jsonb),
  ('growth', 'logos', 'count', '{"max_value":5}'::jsonb),
  ('growth', 'custom_domains', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'custom_domain', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'api_keys', 'count', '{"max_value":3}'::jsonb),
  ('growth', 'webhooks', 'count', '{"max_value":10}'::jsonb),
  ('growth', 'integrations', 'count', '{"max_value":10}'::jsonb),
  ('growth', 'payment_gateways', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'api_requests_day', 'count', '{"max_value":10000}'::jsonb),
  ('growth', 'export_formats', 'export_formats', '{"allowed_formats":"csv,excel,pdf"}'::jsonb),
  ('growth', 'ai_requests_month', 'count', '{"max_value":500}'::jsonb),
  ('growth', 'forecast_jobs', 'count', '{"max_value":20}'::jsonb),
  ('growth', 'report_generation', 'count', '{"max_value":100}'::jsonb),
  ('growth', 'analytics_exports', 'count', '{"max_value":50}'::jsonb),
  ('growth', 'copilot_messages_day', 'count', '{"max_value":150}'::jsonb),
  ('growth', 'otp_messages_month', 'count', '{"max_value":3000}'::jsonb),
  ('growth', 'email_messages_month', 'count', '{"max_value":5000}'::jsonb),
  ('growth', 'push_notifications_month', 'count', '{"max_value":5000}'::jsonb),
  ('growth', 'whatsapp_enabled', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'whatsapp_accounts_max', 'count', '{"max_value":3}'::jsonb),
  ('growth', 'whatsapp_messages_month', 'count', '{"max_value":4000}'::jsonb),
  ('growth', 'whatsapp_concurrency', 'count', '{"max_value":5}'::jsonb),
  ('growth', 'whatsapp_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'whatsapp_customer_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('growth', 'platform_billing', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'products', 'count', '{"max_value":10000}'::jsonb),
  ('scale', 'categories', 'count', '{"max_value":500}'::jsonb),
  ('scale', 'brands', 'count', '{"max_value":500}'::jsonb),
  ('scale', 'product_images', 'count', '{"max_value":35000}'::jsonb),
  ('scale', 'product_variants', 'count', '{"max_value":20000}'::jsonb),
  ('scale', 'attributes', 'count', '{"max_value":5000}'::jsonb),
  ('scale', 'branches', 'count', '{"max_value":15}'::jsonb),
  ('scale', 'warehouses', 'count', '{"max_value":15}'::jsonb),
  ('scale', 'shelves', 'count', '{"max_value":1000}'::jsonb),
  ('scale', 'employees', 'count', '{"max_value":30}'::jsonb),
  ('scale', 'staff_users', 'count', '{"max_value":30}'::jsonb),
  ('scale', 'roles', 'count', '{"max_value":30}'::jsonb),
  ('scale', 'customers', 'count', '{"max_value":50000}'::jsonb),
  ('scale', 'suppliers', 'count', '{"max_value":500}'::jsonb),
  ('scale', 'orders', 'count', '{"max_value":20000}'::jsonb),
  ('scale', 'orders_per_month', 'count', '{"max_value":10000}'::jsonb),
  ('scale', 'active_orders', 'count', '{"max_value":500}'::jsonb),
  ('scale', 'coupons', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'discount_campaigns', 'count', '{"max_value":100}'::jsonb),
  ('scale', 'return_requests', 'count', '{"max_value":1000}'::jsonb),
  ('scale', 'storage_bytes', 'count', '{"max_value":32212254720}'::jsonb),
  ('scale', 'r2_storage', 'count', '{"max_value":32212254720}'::jsonb),
  ('scale', 'uploaded_images', 'count', '{"max_value":35000}'::jsonb),
  ('scale', 'uploaded_files', 'count', '{"max_value":5000}'::jsonb),
  ('scale', 'uploads', 'count', '{"max_value":3000}'::jsonb),
  ('scale', 'banner_images', 'count', '{"max_value":40}'::jsonb),
  ('scale', 'logos', 'count', '{"max_value":10}'::jsonb),
  ('scale', 'custom_domains', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'custom_domain', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'api_keys', 'count', '{"max_value":10}'::jsonb),
  ('scale', 'webhooks', 'count', '{"max_value":30}'::jsonb),
  ('scale', 'integrations', 'count', '{"max_value":30}'::jsonb),
  ('scale', 'payment_gateways', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'api_requests_day', 'count', '{"max_value":50000}'::jsonb),
  ('scale', 'export_formats', 'export_formats', '{"allowed_formats":"csv,excel,pdf"}'::jsonb),
  ('scale', 'ai_requests_month', 'count', '{"max_value":2000}'::jsonb),
  ('scale', 'forecast_jobs', 'count', '{"max_value":100}'::jsonb),
  ('scale', 'report_generation', 'count', '{"max_value":300}'::jsonb),
  ('scale', 'analytics_exports', 'count', '{"max_value":200}'::jsonb),
  ('scale', 'copilot_messages_day', 'count', '{"max_value":500}'::jsonb),
  ('scale', 'otp_messages_month', 'count', '{"max_value":12000}'::jsonb),
  ('scale', 'email_messages_month', 'count', '{"max_value":20000}'::jsonb),
  ('scale', 'push_notifications_month', 'count', '{"max_value":20000}'::jsonb),
  ('scale', 'whatsapp_enabled', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'whatsapp_accounts_max', 'count', '{"max_value":5}'::jsonb),
  ('scale', 'whatsapp_messages_month', 'count', '{"max_value":15000}'::jsonb),
  ('scale', 'whatsapp_concurrency', 'count', '{"max_value":10}'::jsonb),
  ('scale', 'whatsapp_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'whatsapp_customer_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('scale', 'platform_billing', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'products', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'categories', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'brands', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'product_images', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'product_variants', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'attributes', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'branches', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'warehouses', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'shelves', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'employees', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'staff_users', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'roles', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'customers', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'suppliers', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'orders', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'orders_per_month', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'active_orders', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'coupons', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'discount_campaigns', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'return_requests', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'storage_bytes', 'count', '{"max_value":107374182400}'::jsonb),
  ('enterprise', 'r2_storage', 'count', '{"max_value":107374182400}'::jsonb),
  ('enterprise', 'uploaded_images', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'uploaded_files', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'uploads', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'banner_images', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'logos', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'custom_domains', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'custom_domain', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'api_keys', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'webhooks', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'integrations', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'payment_gateways', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'api_requests_day', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'export_formats', 'export_formats', '{"allowed_formats":"csv,excel,pdf"}'::jsonb),
  ('enterprise', 'ai_requests_month', 'count', '{"max_value":10000}'::jsonb),
  ('enterprise', 'forecast_jobs', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'report_generation', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'analytics_exports', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'copilot_messages_day', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'otp_messages_month', 'count', '{"max_value":50000}'::jsonb),
  ('enterprise', 'email_messages_month', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'push_notifications_month', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'whatsapp_enabled', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'whatsapp_accounts_max', 'count', '{"max_value":-1}'::jsonb),
  ('enterprise', 'whatsapp_messages_month', 'count', '{"max_value":50000}'::jsonb),
  ('enterprise', 'whatsapp_concurrency', 'count', '{"max_value":25}'::jsonb),
  ('enterprise', 'whatsapp_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'whatsapp_customer_notifications', 'boolean', '{"enabled":true}'::jsonb),
  ('enterprise', 'platform_billing', 'boolean', '{"enabled":true}'::jsonb)
),
ensured_features AS (
  INSERT INTO public.features (key, display_name)
  SELECT DISTINCT feature_key, feature_key
  FROM seed_data
  ON CONFLICT (key) DO NOTHING
  RETURNING id, key
),
ensured_plan_features AS (
  INSERT INTO public.plan_features (plan_id, feature_id)
  SELECT DISTINCT p.id, f.id
  FROM seed_data sd
  JOIN public.plans p ON p.code = sd.plan_code
  JOIN public.features f ON f.key = sd.feature_key
  ON CONFLICT (plan_id, feature_id) DO NOTHING
  RETURNING id, plan_id, feature_id
)
INSERT INTO public.feature_limits (plan_feature_id, limit_type, limit_config)
SELECT pf.id, sd.limit_type, sd.limit_config
FROM seed_data sd
JOIN public.plans p ON p.code = sd.plan_code
JOIN public.features f ON f.key = sd.feature_key
JOIN public.plan_features pf ON pf.plan_id = p.id AND pf.feature_id = f.id
ON CONFLICT (plan_feature_id, limit_type) DO UPDATE SET limit_config = EXCLUDED.limit_config;
